name: Auto Update MUX Token

on:
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টায়
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} fetch_token.zip


      - name: Run token updater
        run: python fetch_token.py

      - name: Commit changes
        run: |
          rm -rf __pycache__
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "👉 updated M3U8 and Cookie" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
